Repository Argo-swe/ChatSQL, pull requests merged in 2024-06, with the labels that each got.

#20 ARGO-67-Caricamento-del-dizionario-dati
  App/backend/assets/dictionary_schema.json
  App/backend/tools/dictionary_validator.py
  App/backend/tools/utils.py
  App/pages/dictionaries.py
  DizionarioDati/Ordini/ENG/orders.json
Labels: programmatore, sviluppo

#19 Refactoring Index Manager
  App/.gitignore
  App/DizionarioDati/Ordini/ENG/orders.json
  App/DizionarioDati/Ordini/ITA/ordini.json
  App/Indici/orders/idx/config.json
  App/Indici/orders/idx/documents
  App/Indici/orders/idx/indexes/column_description/config.json
  App/Indici/orders/idx/indexes/column_description/embeddings
  App/Indici/orders/idx/indexes/column_description/ids
  App/Indici/orders/idx/indexes/column_description_multilingual/config.json
  App/Indici/orders/idx/indexes/column_description_multilingual/embeddings
  App/Indici/orders/idx/indexes/column_description_multilingual/ids
  App/Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/config.json
  App/Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/embeddings
  App/Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/ids
  App/Indici/orders/idx_complete/config.json
  App/Indici/orders/idx_complete/documents
  App/app_tabs_layout.py
  App/backend/index_manager.py
  App/backend/tools/dictionary_validator.py
  App/backend/tools/schema_multi_extractor.py
  App/index_manager.py
  App/two_indexes.py
  Indici/orders/idx/config.json
  Indici/orders/idx/documents
  Indici/orders/idx/indexes/column_description/config.json
  Indici/orders/idx/indexes/column_description/embeddings
  Indici/orders/idx/indexes/column_description/ids
  Indici/orders/idx/indexes/column_description_multilingual/config.json
  Indici/orders/idx/indexes/column_description_multilingual/embeddings
  Indici/orders/idx/indexes/column_description_multilingual/ids
  Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/config.json
  Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/embeddings
  Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/ids
  Indici/orders/idx_complete/config.json
  Indici/orders/idx_complete/documents
Labels: programmatore, sviluppo, ricerca

#21 Aggiunto DatabaseConnector
  .gitignore
  App/.streamlit/secrets.toml
  App/backend/database_connector.py
  db/schema.sql
Labels: task, programmatore, sviluppo

#22 Aggiunti test d'unità per verificare la ricerca semantica
  .gitignore
  App/.gitignore
  App/backend/index_manager.py
  App/tests/test_index_manager.py
  App/two_indexes.py
Labels: task, programmatore

#24 Modifiche generali alla struttura dei file
  App/frontend/app.py
Labels: programmatore

#28 Modifiche per release 0.0.1
  .github/workflows/build.yml
  .gitignore
  App/.gitignore
  App/DizionarioDati/Ordini/ENG/orders.json
  App/DizionarioDati/Ordini/ITA/ordini.json
  App/__init__.py
  App/backend/assets/Indici/orders/idx/config.json
  App/backend/assets/Indici/orders/idx/documents
  App/backend/assets/Indici/orders/idx/indexes/column_description/config.json
  App/backend/assets/Indici/orders/idx/indexes/column_description/embeddings
  App/backend/assets/Indici/orders/idx/indexes/column_description/ids
  App/backend/assets/Indici/orders/idx/indexes/column_description_multilingual/config.json
  App/backend/assets/Indici/orders/idx/indexes/column_description_multilingual/embeddings
  App/backend/assets/Indici/orders/idx/indexes/column_description_multilingual/ids
  App/backend/assets/Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/config.json
  App/backend/assets/Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/embeddings
  App/backend/assets/Indici/orders/idx/indexes/table_description_with_column_name_and_synonyms/ids
  App/backend/assets/Indici/orders/idx_complete/config.json
  App/backend/assets/Indici/orders/idx_complete/documents
  App/backend/assets/dictionary_schema.json
  App/backend/database_connector.py
  App/backend/index_manager.py
  App/backend/tests/test_index_manager.py
  App/backend/tools/dictionary_validator.py
  App/backend/tools/schema_multi_extractor.py
  App/backend/tools/utils.py
  App/frontend/.streamlit/secrets.toml
  App/frontend/app.py
  App/frontend/assets/favicon.ico
  App/frontend/assets/icon_ai.png
  App/frontend/assets/icon_user.png
  App/frontend/login_interface.py
  App/frontend/pages/dictionaries.py
  db/README.md
  db/schema.sql
Labels: task

#30 Release/0.0.1
  App/backend/index_manager.py
  App/frontend/app.py
Labels: task

#34 Modificato DatabaseConnector
  App/backend/database_connector.py
  App/frontend/.streamlit/secrets.toml
Labels: programmatore

#36 bug Vue con docker 'vite not found'
  docker-compose.yml
  frontend/Dockerfile
Labels: bug, programmatore

#37 Componenti front-end
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/argo_trasparente.png
  frontend/src/assets/main.css
  frontend/src/components/Header.vue
  frontend/src/components/LoginComponent.vue
  frontend/src/components/Logo.vue
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/views/AboutView.vue
  frontend/src/views/DebugView.vue
  frontend/src/views/LoginView.vue
Labels: programmatore, sviluppo

#33 Aggiunti test con modelli locali
  App/.gitignore
  App/backend/index_manager.py
  App/backend/tests/LMStudio/prompt_to_sql_log.txt
  App/backend/tests/LMStudio/test_prompt_generation.py
  App/backend/tests/test_index_manager.py
  App/backend/tools/schema_multi_extractor.py
Labels: programmatore, ricerca

#42 fix parametri FE
  docker-compose.yml
  frontend/package-lock.json
  package-lock.json
Labels: bug, programmatore

#43 ARGO-153-Aggiunta-messaggi-utente-frontend
  frontend/src/layout/AppLayout.vue
  frontend/src/main.ts
  frontend/src/services/toast-message.ts
  frontend/src/views/Login.vue
Labels: programmatore, sviluppo

#40 Feature login
  backend/app/app.py
  backend/app/engine/backend/database_connector.py
  backend/app/engine/backend/jwt_bearer.py
  backend/app/engine/backend/jwt_handler.py
  backend/app/models/login_dto.py
  backend/app/models/responses/auth_response_dto.py
  backend/app/routes/dictionaries_api.py
  backend/app/routes/login_api.py
  backend/app/routes/prompt_api.py
  backend/db/README.md
  backend/db/schema.sql
  backend/requirements.txt
  docker-compose.yml
  frontend/src/services/api-client.ts
  frontend/src/types/openapi.d.ts
  frontend/src/views/Login.vue
Labels: programmatore, sviluppo

#45 Aggiornamenti layout
  frontend/package-lock.json
  frontend/src/assets/fonts/poppins/Poppins-Black.otf
  frontend/src/assets/fonts/poppins/Poppins-BlackItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-Bold.otf
  frontend/src/assets/fonts/poppins/Poppins-BoldItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-ExtraBold.otf
  frontend/src/assets/fonts/poppins/Poppins-ExtraBoldItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-ExtraLight.otf
  frontend/src/assets/fonts/poppins/Poppins-ExtraLightItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-Italic.otf
  frontend/src/assets/fonts/poppins/Poppins-Light.otf
  frontend/src/assets/fonts/poppins/Poppins-LightItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-Medium.otf
  frontend/src/assets/fonts/poppins/Poppins-MediumItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-Regular.otf
  frontend/src/assets/fonts/poppins/Poppins-SemiBold.otf
  frontend/src/assets/fonts/poppins/Poppins-SemiBoldItalic.otf
  frontend/src/assets/fonts/poppins/Poppins-Thin.otf
  frontend/src/assets/fonts/poppins/Poppins-ThinItalic.otf
  frontend/src/assets/layout/_content.scss
  frontend/src/assets/layout/_main.scss
  frontend/src/assets/layout/_responsive.scss
  frontend/src/layout/AppConfig.vue
  frontend/src/layout/AppLayout.vue
  frontend/src/layout/AppMenu.vue
  frontend/src/layout/AppTopbar.vue
  frontend/src/layout/LoginDialog.vue
  frontend/src/layout/composables/layout.js
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/views/Login.vue
  package-lock.json
Labels: task, programmatore, sviluppo

#44 Argo 139 pagina di gestione dei dizionari dati
  .gitignore
  README.md
  backend/.env
  backend/.env-dev
  backend/Dockerfile
  backend/app/database/base.py
  backend/app/database/crud.py
  backend/app/database/models.py
  backend/app/dic_schemas/.gitkeep
  backend/app/dic_schemas/dic_schema_1.json
  backend/app/models/dictionary_dto.py
  backend/app/models/responses/response_dto.py
  backend/app/routes/dictionaries_api.py
  backend/app/routes/login_api.py
  backend/entrypoint-backend.sh
  backend/requirements.txt
  docker-compose.yml
  frontend/Dockerfile
  frontend/entrypoint-frontend.sh
  frontend/src/App.vue
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/router/index.ts
  frontend/src/services/api-client.service.ts
  frontend/src/services/utils.service.ts
  frontend/src/views/DictionariesList.vue
  frontend/src/views/Dizionari.vue
  frontend/src/views/Login.vue
Labels: task, programmatore, sviluppo

#47 fix typo e riferimenti
  backend/.gitignore
  backend/app/routes/dictionaries_api.py
  frontend/src/layout/LoginDialog.vue
Labels: bug, programmatore, hotfix

#49 Pagina Chat
  frontend/public/themes/aura-dark-blue/theme.css
  frontend/public/themes/aura-light-blue/theme.css
  frontend/src/assets/layout/_utils.scss
  frontend/src/main.ts
  frontend/src/views/Chat.vue
  frontend/src/views/Login.vue
  package-lock.json
Labels: task, programmatore, sviluppo
