Repository Argo-swe/ChatSQL, pull requests merged in 2024-05, with the labels that each got.

#5 Prototipo dizionario dati [in inglese]
  App/app.py
  App/index_manager.py
  DizionarioDati/Ordini/ENG/orders.json
  DizionarioDati/Ordini/ITA/ordini.json
Labels: task, progettista

#6 Benchmark modelli
  BenchmarkModelli/benchmark_modelli.py
Labels: task, progettista, programmatore

#8 Prova di traduzione della richiesta utente
  App/two_indexes.py
Labels: programmatore, ricerca

#9 Definizione layout alternativo
  App/app_tabs_layout.py
Labels: programmatore, sviluppo, ricerca

#13 File di configurazione [scopo: generazione artefatto]
  .github/workflows/build.yml
Labels: task, amministratore

#10 Miglioramenti grafici generali
  App/.gitignore
  App/app_tabs_layout.py
  App/assets/favicon.ico
  App/assets/icon_ai.png
  App/assets/icon_user.png
Labels: task, programmatore, sviluppo

#11 Aggiunti i sinonimi della colonna nella ricerca
  App/.gitignore
  App/two_indexes.py
Labels: progettista, programmatore, sviluppo, ricerca

#14 Fix struttura interna artefatto
  .github/workflows/build.yml
Labels: amministratore, hotfix

#15 Aggiunta bozza di classe di estrazione e vecchio file di test
  App/schema_extractor_second_variant.py
  App/schema_multi_extractor.py
Labels: progettista, programmatore, ricerca

#16 Fix errore pubblicazione artefatto
  .github/workflows/build.yml
Labels: bug, amministratore

#17 Visualizzazione anteprima dizionario dati
  App/app_tabs_layout.py
  App/pages/upload_dict.py
Labels: task, programmatore, sviluppo

#18 Aggiunto database engine sqlite
  .gitignore
  db/README.md
  db/schema.sql
Labels: programmatore, sviluppo
