Repository Argo-swe/ChatSQL, pull requests merged in 2024-08, with the labels that each got.

#60 Modifica struttura frontend
  frontend/index.html
  frontend/public/icons/argo_icona.svg
  frontend/public/icons/argo_trasparente.svg
  frontend/public/icons/favicon.ico
  frontend/src/components/AppLogo.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/components/layout/AppConfig.vue
  frontend/src/components/layout/AppFooter.vue
  frontend/src/components/layout/AppMenuItem.vue
  frontend/src/components/layout/AppSidebar.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/composables/layout.js
  frontend/src/router/index.ts
  frontend/src/views/AppLayout.vue
Labels: task, progettista

#61 ARGO-260-Aggiornare-README-per-ChatSQL
  README.md
  frontend/package.json
Labels: documentation

#62 Rivisti requirements e aggiunto pytest
  backend/requirements.txt
Labels: task, programmatore, sviluppo

#59 Update componenti
  backend/requirements.txt
  frontend/public/themes/aura-dark-blue/theme.css
  frontend/src/components/AppLogo.vue
  frontend/src/components/ChatDeleteBtn.vue
  frontend/src/components/DictPreview.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/layout/AppConfig.vue
  frontend/src/components/layout/AppMenu.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/composables/layout.ts
  frontend/src/router/index.ts
  frontend/src/services/message.service.ts
  frontend/src/types/wrapper.ts
  frontend/src/views/AppLayout.vue
  frontend/src/views/ChatView.vue
Labels: programmatore, codifica

#63 Allineamento frontend con il develop
  README.md
  backend/requirements.txt
  frontend/index.html
  frontend/public/icons/argo_icona.svg
  frontend/public/icons/argo_trasparente.svg
  frontend/public/icons/favicon.ico
  frontend/public/themes/aura-dark-blue/theme.css
  frontend/src/components/AppLogo.vue
  frontend/src/components/ChatDeleteBtn.vue
  frontend/src/components/DictPreview.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/Logo.vue
  frontend/src/components/icons/IconCommunity.vue
  frontend/src/components/icons/IconDocumentation.vue
  frontend/src/components/icons/IconEcosystem.vue
  frontend/src/components/icons/IconSupport.vue
  frontend/src/components/icons/IconTooling.vue
  frontend/src/components/layout/AppConfig.vue
  frontend/src/components/layout/AppFooter.vue
  frontend/src/components/layout/AppMenu.vue
  frontend/src/components/layout/AppMenuItem.vue
  frontend/src/components/layout/AppSidebar.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/composables/layout.ts
  frontend/src/router/index.ts
  frontend/src/services/message.service.ts
  frontend/src/types/wrapper.ts
  frontend/src/views/AppLayout.vue
  frontend/src/views/ChatView.vue
Labels: task

#65 Aggiornamento componenti Layout
  README.md
  backend/requirements.txt
  frontend/package.json
  frontend/src/assets/layout/_footer.scss
  frontend/src/components/LoginDialog.vue
  frontend/src/components/layout/AppFooter.vue
  frontend/src/components/layout/AppMenu.vue
  frontend/src/components/layout/AppMenuItem.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/components/layout/ConfigSidebar.vue
  frontend/src/components/layout/MenuSidebar.vue
  frontend/src/composables/check-click.ts
  frontend/src/types/wrapper.ts
  frontend/src/views/AppLayout.vue
  frontend/src/views/ChatView.vue
Labels: progettista, programmatore, codifica

#67 Aggiunti file di configurazione iniziale Jest
  frontend/jest.config.js
  frontend/package.json
  frontend/src/views/ChatView.vue
  frontend/tests/services/utils.service.test.ts
  frontend/tsconfig.test.json
  package-lock.json
  package.json
Labels: sviluppo, ricerca, codifica

#66 Aggiornamento componenti [src/components]
  frontend/src/App.vue
  frontend/src/components/AppLogo.vue
  frontend/src/components/ChatDeleteBtn.vue
  frontend/src/components/ChatMessage.vue
  frontend/src/components/DictPreview.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/composables/layout.ts
  frontend/src/locales/en.json
  frontend/src/locales/it.json
  frontend/src/main.ts
  frontend/src/router/index.ts
  frontend/src/services/api-client.service.ts
  frontend/src/services/auth.service.ts
  frontend/src/services/message.service.ts
  frontend/src/services/utils.service.ts
  frontend/src/types/wrapper.ts
  frontend/src/views/AppLayout.vue
Labels: task, progettista, codifica

#68 Aggiornamento dictionary modal
  frontend/src/components/AppLogo.vue
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/composables/CreateUpdateDictionary/shared-state.ts
  frontend/src/composables/CreateUpdateDictionary/status-messages.ts
  frontend/src/locales/en.json
  frontend/src/locales/it.json
  frontend/src/main.ts
  frontend/src/types/wrapper.ts
Labels: task, progettista, codifica

#70 Aggiornamento dictionary view - chat view
  frontend/src/components/ChatMessage.vue
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/layout/AppMenuItem.vue
  frontend/src/composables/CreateUpdateDictionary/shared-state.ts
  frontend/src/composables/CreateUpdateDictionary/status-messages.ts
  frontend/src/composables/status-messages.ts
  frontend/src/main.ts
  frontend/src/types/wrapper.ts
  frontend/src/views/ChatView.vue
  frontend/src/views/DictionariesListView.vue
Labels: task, progettista, codifica

#64 Aggiornamento workflow [PB]
  .github/workflows/build.yml
  frontend/cypress.config.js
  frontend/cypress/fixtures/.gitkeep
  frontend/cypress/support/commands.ts
  frontend/cypress/support/component-index.html
  frontend/cypress/support/component.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/component/App.cy.ts
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: task, amministratore

#72 Feature debug demo [from #69 & #70]
  backend/app/engine/debug_manager.py
  backend/app/engine/index_manager.py
  backend/app/engine/prompt_manager.py
  backend/app/models/prompt_dto.py
  backend/app/models/responses/prompt_response_dto.py
  backend/app/routes/prompt_api.py
  backend/app/tools/utils.py
  frontend/src/components/ChatMessage.vue
  frontend/src/components/DebugMessage.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/StringDataModal.vue
  frontend/src/locales/en.json
  frontend/src/locales/it.json
  frontend/src/types/openapi.d.ts
  frontend/src/types/wrapper.ts
  frontend/src/views/ChatView.vue
Labels: task, progettista, codifica, allineamento

#73 Allineamento frontend con il develop
  .github/workflows/build.yml
Labels: task, allineamento

#75 Delete package-lock.json
  .github/workflows/build.yml
  package-lock.json
Labels: allineamento

#77 Fix frontend [type check]
  .github/workflows/build.yml
  frontend/src/components/DebugMessage.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/layout/AppMenu.vue
  frontend/src/composables/status-messages.ts
Labels: hotfix

#78 Test FE AppLogo
  frontend/tests/component/AppLogo.cy.ts
Labels: programmatore, codifica

#80 Fix bug FE + test pulsante + update package json
  frontend/.gitignore
  frontend/package.json
  frontend/src/components/ChatDeleteBtn.vue
  frontend/tests/component/AppLogo.cy.ts
  frontend/tests/component/ChatDeleteBtn.cy.ts
Labels: bug, progettista, hotfix, test

#83 Correzioni minime
  frontend/src/locales/en.json
  frontend/src/locales/it.json
  frontend/src/views/ChatView.vue
Labels: programmatore, codifica

#81 Aggiunti test FE debug message e string data modal
  frontend/src/components/DebugMessage.vue
  frontend/tests/component/DebugMessage.cy.ts
  frontend/tests/component/StringDataModal.cy.ts
Labels: task, progettista, test

#84 Fix test + aggiunti test dict preview e chat message
  frontend/src/components/ChatMessage.vue
  frontend/src/components/DictPreview.vue
  frontend/tests/component/ChatDeleteBtn.cy.ts
  frontend/tests/component/ChatMessage.cy.ts
  frontend/tests/component/DebugMessage.cy.ts
  frontend/tests/component/DictPreview.cy.ts
  frontend/tests/component/StringDataModal.cy.ts
Labels: task, progettista, programmatore, test

#85 Aggiornamento workflow
  .github/workflows/build.yml
Labels: hotfix

#89 Aggiunti messaggi di errore [da exceptions.py]
  backend/app/core/port/outcoming/embeddings/embeddings_abstract_factory.py
  backend/app/core/service/authentication_service.py
  backend/app/core/service/dictionary_service.py
  backend/app/core/service/prompt_manager_service.py
  backend/app/routes/auth/jwt_bearer.py
  backend/app/routes/dictionaries_api.py
  backend/app/tools/exceptions.py
Labels: task, programmatore

#87 Test per txtai
  .github/workflows/build.yml
  .pre-commit-config.yaml
  backend/app/models/dictionary_dto.py
  backend/app/models/dictionary_internal_structure/table_dto.py
  backend/app/models/dictionary_preview_dto.py
  backend/app/tests/__init__.py
  backend/app/tests/txtai/__init__.py
  backend/app/tests/txtai/test_txtai_debug_manager_adapter.py
  backend/app/tests/txtai/test_txtai_embeddings_manager_factory.py
  backend/app/tests/txtai/test_txtai_index_manager_adapter.py
  backend/app/tests/txtai/test_txtai_prompt_manager_adapter.py
  backend/requirements.txt
Labels: test

#92 ARGO-305-Test-BE-json-validator-e-utils
  backend/app/tests/adapter/__init__.py
  backend/app/tests/adapter/incoming/__init__.py
  backend/app/tests/adapter/incoming/test_json_schema_validator_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/__init__.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/__init__.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_debug_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_embeddings_manager_factory.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_index_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_prompt_manager_adapter.py
  backend/app/tests/assets/example_schema.json
  backend/app/tests/assets/example_schema_wrong.json
  backend/app/tests/assets/simple_json.json
  backend/app/tests/assets/wrong_json.json
  backend/app/tests/tools/__init__.py
  backend/app/tests/tools/test_tools_utils.py
  backend/app/tools/utils.py
Labels: sviluppo, test

#90 Aggiungere commenti back-end
  backend/app/adapter/outcoming/db_manager/sql_alchemy/models.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_authentication_repository_adapter.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_dictionary_repository_adapter.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_debug_manager_adapter.py
  backend/app/adapter/outcoming/file/json_file_adapter.py
  backend/app/app.py
  backend/app/configuration.py
  backend/app/core/port/incoming/authentication_use_case.py
  backend/app/core/port/incoming/dictionary_use_case.py
  backend/app/core/port/incoming/prompt_use_case.py
  backend/app/core/port/incoming/schema_validator_use_case.py
  backend/app/core/port/outcoming/authentication_repository.py
  backend/app/core/port/outcoming/db_manager_abstract_factory.py
  backend/app/core/port/outcoming/dictionary_repository.py
  backend/app/core/port/outcoming/embeddings/debug_manager_port.py
  backend/app/core/port/outcoming/embeddings/embeddings_abstract_factory.py
  backend/app/core/port/outcoming/embeddings/index_manager_port.py
  backend/app/core/port/outcoming/embeddings/prompt_manager_port.py
  backend/app/core/port/outcoming/file_repository.py
  backend/app/core/service/authentication_service.py
  backend/app/core/service/dictionary_service.py
  backend/app/core/service/prompt_manager_service.py
  backend/app/models/admin_dto.py
  backend/app/routes/dictionaries_api.py
  backend/app/routes/login_api.py
  backend/app/routes/prompt_api.py
  backend/app/tools/exceptions.py
  backend/app/tools/log_filter.py
  backend/app/tools/utils.py
Labels: task, programmatore, codifica

#88 Setup test login dialog + fix async function
  frontend/src/components/ChatMessage.vue
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/services/api-client.service.ts
  frontend/src/services/message.service.ts
  frontend/src/views/ChatView.vue
  frontend/src/views/DictionariesListView.vue
  frontend/tests/component/LoginDialog.cy.ts
Labels: task, progettista, programmatore, test

#93 ARGO-318-Implementazione-test-BE-services
  backend/app/adapter/outcoming/file/json_file_adapter.py
  backend/app/core/port/outcoming/file_repository.py
  backend/app/core/service/prompt_manager_service.py
  backend/app/tests/adapter/outcoming/test_json_file_adapter.py
  backend/app/tests/core/__init__.py
  backend/app/tests/core/services/__init__.py
  backend/app/tests/core/services/test_authentication_service.py
  backend/app/tests/core/services/test_dictionary_service.py
  backend/app/tests/core/services/test_prompt_manager_service.py
  backend/app/tools/exceptions.py
  backend/requirements.txt
Labels: programmatore, sviluppo, test

#94 aggiunta coverage test BE
  README.md
  backend/.gitignore
  backend/Dockerfile
  backend/app/.coveragerc
  backend/app/core/port/incoming/authentication_use_case.py
  backend/app/core/port/incoming/dictionary_use_case.py
  backend/app/core/port/incoming/prompt_use_case.py
  backend/app/core/port/incoming/schema_validator_use_case.py
  backend/app/core/port/outcoming/authentication_repository.py
  backend/app/core/port/outcoming/db_manager_abstract_factory.py
  backend/app/core/port/outcoming/dictionary_repository.py
  backend/app/core/port/outcoming/embeddings/debug_manager_port.py
  backend/app/core/port/outcoming/embeddings/embeddings_abstract_factory.py
  backend/app/core/port/outcoming/embeddings/index_manager_port.py
  backend/app/core/port/outcoming/embeddings/prompt_manager_port.py
  backend/app/core/port/outcoming/file_repository.py
  backend/app/core/service/dictionary_service.py
  backend/app/coverage.xml
  backend/app/models/admin_dto.py
  backend/app/routes/auth/jwt_handler.py
  backend/app/tests/core/services/test_dictionary_service.py
  backend/app/tests/routes/__init__.py
  backend/app/tests/routes/test_auth_jwt_handler.py
  backend/requirements.txt
Labels: programmatore, sviluppo, test

#96 Test BE SQLAlchemy
  backend/app/adapter/outcoming/db_manager/sql_alchemy/base.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_dictionary_repository_adapter.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_authentication_repository_adapter.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_db_manager_factory.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_dictionary_repository_adapter.py
  backend/app/tests/adapter/outcoming/db_manager/test_db_manager_factory.py
Labels: test

#97 Test front-end Services [jest]
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/services/utils.service.ts
  frontend/tests/services/auth.service.test.ts
  frontend/tests/services/utils.service.test.ts
Labels: task, test

#95 Test front-end Dictionary Modal e Views
  frontend/cypress/fixtures/.gitkeep
  frontend/cypress/fixtures/invalid_orders.json
  frontend/cypress/fixtures/orders.json
  frontend/cypress/fixtures/orders.txt
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/types/wrapper.ts
  frontend/src/views/ChatView.vue
  frontend/src/views/DictionariesListView.vue
  frontend/tests/component/ChatDeleteBtn.cy.ts
  frontend/tests/component/ChatMessage.cy.ts
  frontend/tests/component/CreateUpdateDictionaryModal.cy.ts
  frontend/tests/component/DebugMessage.cy.ts
  frontend/tests/component/DictPreview.cy.ts
  frontend/tests/component/LoginDialog.cy.ts
  frontend/tests/component/StringDataModal.cy.ts
  frontend/tests/component/views/ChatView.cy.ts
  frontend/tests/component/views/DictionariesListView.cy.ts
Labels: task, progettista, programmatore, test

#99 aggiunti nel codice i requisiti mancanti
  backend/app/adapter/incoming/schema_validator/json_schema_validator_adapter.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/base.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_prompt_manager_adapter.py
  backend/app/core/service/dictionary_service.py
  backend/app/models/dictionary_dto.py
  backend/app/models/prompt_dto.py
  backend/app/tests/adapter/incoming/test_json_schema_validator_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_prompt_manager_adapter.py
  backend/app/tools/exceptions.py
  frontend/src/components/ChatMessage.vue
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/locales/en.json
  frontend/src/locales/it.json
  frontend/src/types/wrapper.ts
  frontend/src/views/ChatView.vue
  frontend/tests/component/CreateUpdateDictionaryModal.cy.ts
Labels: programmatore, sviluppo

#91 Test FE layout
  frontend/cypress.config.js
  frontend/src/components/AppLogo.vue
  frontend/src/components/layout/AppFooter.vue
  frontend/src/components/layout/AppMenu.vue
  frontend/src/components/layout/AppMenuItem.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/components/layout/ConfigSidebar.vue
  frontend/src/components/layout/MenuSidebar.vue
  frontend/src/composables/layout.ts
  frontend/tests/component/App.cy.ts
  frontend/tests/component/AppLogo.cy.ts
  frontend/tests/component/layout/AppFooter.cy.ts
  frontend/tests/component/layout/AppMenu.cy.ts
  frontend/tests/component/layout/AppMenuItem.cy.ts
  frontend/tests/component/layout/AppTopbar.cy.ts
  frontend/tests/component/layout/ConfigSidebar.cy.ts
  frontend/tests/component/layout/MenuSidebar.cy.ts
Labels: programmatore, test

#98 Configurazione test e2e
  .github/workflows/build.yml
  backend/app/adapter/outcoming/embeddings/txtai/txtai_embeddings_manager_factory.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_index_manager_adapter.py
  backend/app/core/service/dictionary_service.py
  backend/app/models/dictionary_dto.py
  backend/app/models/responses/response_dto.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_embeddings_manager_factory.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_index_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_prompt_manager_adapter.py
  backend/app/tests/adapter/outcoming/file/__init__.py
  backend/app/tests/adapter/outcoming/file/test_json_file_adapter.py
  backend/app/tests/routes/test_auth_jwt_handler.py
  backend/app/tests/tools/test_tools_utils.py
  backend/config.json
  frontend/.gitignore
  frontend/cypress.config.js
  frontend/cypress/fixtures/cinema.json
  frontend/cypress/fixtures/orders.json
  frontend/cypress/fixtures/too_large_file.json
  frontend/cypress/support/commands.ts
  frontend/cypress/support/component.ts
  frontend/cypress/support/e2e.ts
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/CreateUpdateDictionaryModal.vue
  frontend/src/components/LoginDialog.vue
  frontend/src/components/layout/AppTopbar.vue
  frontend/src/components/layout/ConfigSidebar.vue
  frontend/src/composables/status-messages.ts
  frontend/src/locales/en.json
  frontend/src/locales/it.json
  frontend/src/types/openapi.d.ts
  frontend/src/views/AppLayout.vue
  frontend/src/views/ChatView.vue
  frontend/tests/component/CreateUpdateDictionaryModal.cy.ts
  frontend/tests/component/layout/ConfigSidebar.cy.ts
  frontend/tests/e2e/chat.cy.ts
  frontend/tests/e2e/chatAdmin.ts
  frontend/tests/e2e/dictionary.cy.ts
  frontend/tests/e2e/login.cy.ts
  frontend/tests/e2e/settings.cy.ts
  frontend/tests/services/utils.service.test.ts
Labels: codifica, test
