Repository Argo-swe/ChatSQL, pull requests merged in 2024-09, with the labels that each got.

#101 Aggiornamento algoritmo txtai
  .github/workflows/build.yml
  README.md
  backend/app/adapter/outcoming/embeddings/txtai/txtai_debug_manager_adapter.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_prompt_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_debug_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_embeddings_manager_factory.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_prompt_manager_adapter.py
  backend/app/tests/adapter/outcoming/file/test_file_factory.py
  backend/app/tests/adapter/outcoming/file/test_json_file_adapter.py
Labels: task, progettista, programmatore, test

#104 Aggiunto badge corretto al README
  .github/workflows/build.yml
  README.md
  backend/app/tests/routes/test_auth_jwt_handler.py
  frontend/cypress.config.js
  frontend/cypress/support/component.ts
  frontend/cypress/support/e2e.ts
  frontend/vite.config.ts
Labels: task

#103 modificati tipi di ritorno con le relative interfacce
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_db_manager_factory.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_embeddings_manager_factory.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_prompt_manager_adapter.py
Labels: task, programmatore

#105 Update README.md
  README.md
Labels: task

#106 Update build.yml
  .github/workflows/build.yml
Labels: task

#107 Update build.yml
  .github/workflows/build.yml
Labels: task

#108 Fix front-end e back-end [pre-release]
  backend/app/adapter/incoming/schema_validator/json_schema_validator_adapter.py
  backend/app/adapter/incoming/schema_validator/schema_validator_factory.py
  backend/app/adapter/outcoming/db_manager/db_manager_factory.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_authentication_repository_adapter.py
  backend/app/adapter/outcoming/embeddings/embeddings_manager_factory.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_debug_manager_adapter.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_embeddings_manager_factory.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_index_manager_adapter.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_prompt_manager_adapter.py
  backend/app/adapter/outcoming/embeddings/txtai/txtai_search_algorithm_adapter.py
  backend/app/adapter/outcoming/file/file_factory.py
  backend/app/adapter/outcoming/file/json_file_adapter.py
  backend/app/app.py
  backend/app/configuration.py
  backend/app/core/port/incoming/dictionary_use_case.py
  backend/app/core/port/incoming/prompt_use_case.py
  backend/app/core/port/incoming/schema_validator_use_case.py
  backend/app/core/port/outcoming/authentication_repository.py
  backend/app/core/port/outcoming/embeddings/debug_manager_port.py
  backend/app/core/port/outcoming/embeddings/embeddings_abstract_factory.py
  backend/app/core/port/outcoming/embeddings/index_manager_port.py
  backend/app/core/port/outcoming/embeddings/prompt_manager_port.py
  backend/app/core/port/outcoming/embeddings/search_algorithm_port.py
  backend/app/core/port/outcoming/file_repository.py
  backend/app/core/service/authentication_service.py
  backend/app/core/service/dictionary_service.py
  backend/app/core/service/prompt_manager_service.py
  backend/app/models/admin_dto.py
  backend/app/models/dictionary_dto.py
  backend/app/models/dictionary_internal_structure/table_dto.py
  backend/app/models/dictionary_preview_dto.py
  backend/app/models/login_dto.py
  backend/app/models/prompt_dto.py
  backend/app/models/responses/auth_response_dto.py
  backend/app/models/responses/dictionaries_response_dto.py
  backend/app/models/responses/dictionary_response_dto.py
  backend/app/models/responses/prompt_response_dto.py
  backend/app/models/responses/response_dto.py
  backend/app/models/responses/string_data_response_dto.py
  backend/app/routes/auth/jwt_bearer.py
  backend/app/routes/auth/jwt_handler.py
  backend/app/routes/dictionaries_api.py
  backend/app/routes/login_api.py
  backend/app/routes/prompt_api.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_authentication_repository_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_debug_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_prompt_manager_adapter.py
  backend/app/tests/adapter/outcoming/embeddings/txtai/test_txtai_search_algorithm_adapter.py
  backend/app/tests/adapter/outcoming/file/test_json_file_adapter.py
  backend/app/tests/core/services/test_authentication_service.py
  backend/app/tests/core/services/test_dictionary_service.py
  backend/app/tools/exceptions.py
  frontend/src/types/openapi.d.ts
  frontend/src/views/ChatView.vue
  frontend/tests/component/views/DictionariesListView.cy.ts
Labels: programmatore, codifica

#111 Creato docker compose rilascio
  .github/workflows/build.yml
  README.md
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_authentication_repository_adapter.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_dictionary_repository_adapter.py
  backend/app/core/port/outcoming/authentication_repository.py
  backend/app/core/port/outcoming/dictionary_repository.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_authentication_repository_adapter.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_dictionary_repository_adapter.py
  docker-compose-production.yml
  frontend/.env
  frontend/src/locales/it.json
Labels: programmatore, release

#113 Allineamento develop (post release)
  .github/workflows/build.yml
  README.md
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_authentication_repository_adapter.py
  backend/app/adapter/outcoming/db_manager/sql_alchemy/sql_alchemy_dictionary_repository_adapter.py
  backend/app/core/port/outcoming/authentication_repository.py
  backend/app/core/port/outcoming/dictionary_repository.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_authentication_repository_adapter.py
  backend/app/tests/adapter/outcoming/db_manager/sql_alchemy/test_sql_alchemy_dictionary_repository_adapter.py
  docker-compose-production.yml
  frontend/.env
  frontend/src/locales/it.json
Labels: allineamento
